### ISSUE TITLE
Chyba JOJ.SK 

### ISSUE THREAD

**Issue by hitman222** [kodi-czsk/plugin.video.joj.sk#17]
Vyskakuje chyba informace v logu.Posílám log.Děkuji.

[log-2016-11-18-09.43.52.zip](https://github.com/kodi-czsk/plugin.video.joj.sk/files/599561/log-2016-11-18-09.43.52.zip)

**Comment by mx3L** [comment]
Ahoj,
z logu som vycital tuto chybu:
```
10:42:26 80811.750000 T:1371534240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('headers',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.joj.sk/default.py", line 52, in <module>
                                                XBMCJojContentProvider(provider,settings,__addon__).run(params)
                                              File "/storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 71, in run
                                                return self.play({'url':params['play'],'info':params})
                                              File "/storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 193, in play
                                                xbmcutil.load_subtitles(stream['subs'], stream['headers'])
                                            KeyError: ('headers',)
                                            -->End of Python script error report<--
```
Tato chyba bola opravena v script.module.stream.resolver 1.6.44 verzii
